// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feeabstraction/absfee/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the feeabs module.
type Params struct {
	// only ibc osmosis is allowed to be used as fee token
	// this is the ibc denom of osmosis
	OsmosisIbcDenom string `protobuf:"bytes,1,opt,name=osmosis_ibc_denom,json=osmosisIbcDenom,proto3" json:"osmosis_ibc_denom,omitempty" yaml:"allowed_token"`
	// connection id to osmosis chain
	OsmosisIbcConnectionId string `protobuf:"bytes,2,opt,name=osmosis_ibc_connection_id,json=osmosisIbcConnectionId,proto3" json:"osmosis_ibc_connection_id,omitempty"`
	// contract on osmosis with custom ibc logic for fetching spot price
	OsmosisQueryContract string `protobuf:"bytes,3,opt,name=osmosis_query_contract,json=osmosisQueryContract,proto3" json:"osmosis_query_contract,omitempty"`
	// we'll update the fee rate each `fee_rate_update_period`
	FeeRateUpdatePeriod time.Duration `protobuf:"bytes,4,opt,name=fee_rate_update_period,json=feeRateUpdatePeriod,proto3,stdduration" json:"fee_rate_update_period"`
	// we'll swap our accumulated ibc fee to native token each `accumulated_fee_swap_period`
	AccumulatedFeeSwapPeriod time.Duration `protobuf:"bytes,5,opt,name=accumulated_fee_swap_period,json=accumulatedFeeSwapPeriod,proto3,stdduration" json:"accumulated_fee_swap_period"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e66a0978c84086, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetOsmosisIbcDenom() string {
	if m != nil {
		return m.OsmosisIbcDenom
	}
	return ""
}

func (m *Params) GetOsmosisIbcConnectionId() string {
	if m != nil {
		return m.OsmosisIbcConnectionId
	}
	return ""
}

func (m *Params) GetOsmosisQueryContract() string {
	if m != nil {
		return m.OsmosisQueryContract
	}
	return ""
}

func (m *Params) GetFeeRateUpdatePeriod() time.Duration {
	if m != nil {
		return m.FeeRateUpdatePeriod
	}
	return 0
}

func (m *Params) GetAccumulatedFeeSwapPeriod() time.Duration {
	if m != nil {
		return m.AccumulatedFeeSwapPeriod
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "feeabstraction.absfee.v1beta1.Params")
}

func init() {
	proto.RegisterFile("feeabstraction/absfee/v1beta1/params.proto", fileDescriptor_64e66a0978c84086)
}

var fileDescriptor_64e66a0978c84086 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xe3, 0x02, 0x15, 0x98, 0x03, 0xc2, 0x44, 0x95, 0x1b, 0xc0, 0xa9, 0x72, 0xaa, 0x2a,
	0xe1, 0x55, 0x80, 0x4b, 0x39, 0xa6, 0x11, 0x52, 0x6f, 0x25, 0x15, 0x12, 0xe2, 0x62, 0xcd, 0xda,
	0x63, 0xb3, 0xc2, 0xde, 0x59, 0xbc, 0xeb, 0x86, 0x7c, 0x0b, 0x8e, 0x7c, 0xa4, 0x1e, 0x7b, 0xe4,
	0x54, 0x50, 0xf2, 0x0d, 0xb8, 0x23, 0xa1, 0xdd, 0x6c, 0x20, 0x70, 0xea, 0xc9, 0x7f, 0xde, 0x7b,
	0xbf, 0xd9, 0x79, 0xda, 0xf0, 0xa8, 0x44, 0x04, 0xae, 0x4d, 0x0b, 0xb9, 0x11, 0x24, 0x19, 0x70,
	0x5d, 0x22, 0xb2, 0x8b, 0x31, 0x47, 0x03, 0x63, 0xa6, 0xa0, 0x85, 0x46, 0xa7, 0xaa, 0x25, 0x43,
	0xd1, 0xd3, 0x7f, 0xbd, 0xe9, 0xda, 0x9b, 0x7a, 0xef, 0xa0, 0x5f, 0x51, 0x45, 0xce, 0xc9, 0xec,
	0xdb, 0x3a, 0x34, 0x78, 0x52, 0x11, 0x55, 0x35, 0x32, 0x50, 0x82, 0x81, 0x94, 0x64, 0xc0, 0x66,
	0x3d, 0x72, 0x70, 0x94, 0x93, 0x6e, 0x48, 0x33, 0x0e, 0x1a, 0xd9, 0xa7, 0x0e, 0xdb, 0xc5, 0xd6,
	0xe8, 0x4a, 0x48, 0x67, 0xf6, 0xde, 0xc4, 0x93, 0xdc, 0x17, 0xef, 0x4a, 0x56, 0x74, 0xed, 0x96,
	0x3e, 0xfa, 0xb5, 0x13, 0xee, 0x9e, 0xb9, 0xf3, 0x46, 0xd3, 0xf0, 0xa1, 0xe3, 0x0a, 0x9d, 0x09,
	0x9e, 0x67, 0x05, 0x4a, 0x6a, 0xe2, 0xe0, 0x20, 0x38, 0xbc, 0x37, 0x89, 0x7f, 0x5e, 0x0f, 0xfb,
	0x0b, 0x68, 0xea, 0x57, 0x23, 0xa8, 0x6b, 0x9a, 0x63, 0x91, 0x19, 0xfa, 0x88, 0x72, 0x34, 0x7b,
	0xe0, 0x23, 0xa7, 0x3c, 0x9f, 0xda, 0x40, 0x74, 0x1c, 0xee, 0x6f, 0x53, 0x72, 0x92, 0x12, 0xdd,
	0xe6, 0x99, 0x28, 0xe2, 0x1d, 0x4b, 0x9b, 0xed, 0xfd, 0xcd, 0x9c, 0xfc, 0x91, 0x4f, 0x8b, 0xe8,
	0x65, 0xb8, 0x51, 0x32, 0xb7, 0x95, 0x0d, 0xbb, 0xde, 0xe2, 0x5b, 0x2e, 0xd7, 0xf7, 0xea, 0x1b,
	0x2b, 0x9e, 0x78, 0x2d, 0x7a, 0x17, 0xee, 0x95, 0x88, 0x59, 0x0b, 0x06, 0xb3, 0x4e, 0x15, 0xf6,
	0xa1, 0xb0, 0x15, 0x54, 0xc4, 0xb7, 0x0f, 0x82, 0xc3, 0xfb, 0xcf, 0xf7, 0xd3, 0x75, 0x05, 0xe9,
	0xa6, 0x82, 0x74, 0xea, 0x2b, 0x98, 0xdc, 0xbd, 0xbc, 0x1e, 0xf6, 0xbe, 0x7e, 0x1f, 0x06, 0xb3,
	0x47, 0x25, 0xe2, 0x0c, 0x0c, 0xbe, 0x75, 0x80, 0x33, 0x97, 0x8f, 0x78, 0xf8, 0x18, 0xf2, 0xbc,
	0x6b, 0xba, 0x1a, 0x0c, 0x16, 0x99, 0x9d, 0xa2, 0xe7, 0xa0, 0x36, 0xf8, 0x3b, 0x37, 0xc7, 0xc7,
	0x5b, 0x9c, 0xd7, 0x88, 0xe7, 0x73, 0x50, 0xeb, 0x19, 0x93, 0xf3, 0xcb, 0x65, 0x12, 0x5c, 0x2d,
	0x93, 0xe0, 0xc7, 0x32, 0x09, 0xbe, 0xac, 0x92, 0xde, 0xd5, 0x2a, 0xe9, 0x7d, 0x5b, 0x25, 0xbd,
	0xf7, 0xc7, 0x95, 0x30, 0x1f, 0x3a, 0x9e, 0xe6, 0xd4, 0x30, 0x49, 0x16, 0x08, 0xf5, 0xb3, 0x1a,
	0xb8, 0x66, 0xff, 0xdd, 0xbe, 0x8b, 0x31, 0xfb, 0xec, 0xff, 0x31, 0xb3, 0x50, 0xa8, 0xf9, 0xae,
	0x3b, 0xcb, 0x8b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xea, 0xee, 0x41, 0xa8, 0x02, 0x00,
	0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.AccumulatedFeeSwapPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AccumulatedFeeSwapPeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.FeeRateUpdatePeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FeeRateUpdatePeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	if len(m.OsmosisQueryContract) > 0 {
		i -= len(m.OsmosisQueryContract)
		copy(dAtA[i:], m.OsmosisQueryContract)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OsmosisQueryContract)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OsmosisIbcConnectionId) > 0 {
		i -= len(m.OsmosisIbcConnectionId)
		copy(dAtA[i:], m.OsmosisIbcConnectionId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OsmosisIbcConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OsmosisIbcDenom) > 0 {
		i -= len(m.OsmosisIbcDenom)
		copy(dAtA[i:], m.OsmosisIbcDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OsmosisIbcDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OsmosisIbcDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OsmosisIbcConnectionId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OsmosisQueryContract)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FeeRateUpdatePeriod)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AccumulatedFeeSwapPeriod)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisIbcDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisIbcDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisIbcConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisIbcConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisQueryContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisQueryContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeRateUpdatePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.FeeRateUpdatePeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumulatedFeeSwapPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.AccumulatedFeeSwapPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
