// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feeabstraction/absfee/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the feeabs module.
type Params struct {
	// only ibc osmosis is allowed to be used as fee token
	// this is the ibc denom of osmosis
	OsmosisIbcDenom string `protobuf:"bytes,1,opt,name=osmosis_ibc_denom,json=osmosisIbcDenom,proto3" json:"osmosis_ibc_denom,omitempty" yaml:"allowed_token"`
	// IBC denom of native token in osmosis chain
	NativeIbcDenom string `protobuf:"bytes,2,opt,name=native_ibc_denom,json=nativeIbcDenom,proto3" json:"native_ibc_denom,omitempty" yaml:"allowed_token"`
	// connection id to osmosis chain
	OsmosisQueryChannel string `protobuf:"bytes,3,opt,name=osmosis_query_channel,json=osmosisQueryChannel,proto3" json:"osmosis_query_channel,omitempty"`
	// connection id to osmosis chain
	OsmosisTransferChannel string `protobuf:"bytes,4,opt,name=osmosis_transfer_channel,json=osmosisTransferChannel,proto3" json:"osmosis_transfer_channel,omitempty"`
	// connection id to osmosis chain
	OsmosisSwapChannel string `protobuf:"bytes,5,opt,name=osmosis_swap_channel,json=osmosisSwapChannel,proto3" json:"osmosis_swap_channel,omitempty"`
	// contract on osmosis with custom ibc logic for fetching spot price
	OsmosisQueryContract string `protobuf:"bytes,6,opt,name=osmosis_query_contract,json=osmosisQueryContract,proto3" json:"osmosis_query_contract,omitempty"`
	// contract on osmosis with custom ibc logic for fetching spot price
	OsmosisSwapContract string `protobuf:"bytes,7,opt,name=osmosis_swap_contract,json=osmosisSwapContract,proto3" json:"osmosis_swap_contract,omitempty"`
	// pool id
	PoolId uint64 `protobuf:"varint,8,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// we'll update the fee rate each `osmosis_exchange_rate_update_period`
	OsmosisExchangeRateUpdatePeriod time.Duration `protobuf:"bytes,9,opt,name=osmosis_exchange_rate_update_period,json=osmosisExchangeRateUpdatePeriod,proto3,stdduration" json:"osmosis_exchange_rate_update_period"`
	// we'll swap our accumulated osmosis fee to native token each `accumulated_osmosis_fee_swap_period`
	AccumulatedOsmosisFeeSwapPeriod time.Duration `protobuf:"bytes,10,opt,name=accumulated_osmosis_fee_swap_period,json=accumulatedOsmosisFeeSwapPeriod,proto3,stdduration" json:"accumulated_osmosis_fee_swap_period"`
	// Active
	Active bool `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e66a0978c84086, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetOsmosisIbcDenom() string {
	if m != nil {
		return m.OsmosisIbcDenom
	}
	return ""
}

func (m *Params) GetNativeIbcDenom() string {
	if m != nil {
		return m.NativeIbcDenom
	}
	return ""
}

func (m *Params) GetOsmosisQueryChannel() string {
	if m != nil {
		return m.OsmosisQueryChannel
	}
	return ""
}

func (m *Params) GetOsmosisTransferChannel() string {
	if m != nil {
		return m.OsmosisTransferChannel
	}
	return ""
}

func (m *Params) GetOsmosisSwapChannel() string {
	if m != nil {
		return m.OsmosisSwapChannel
	}
	return ""
}

func (m *Params) GetOsmosisQueryContract() string {
	if m != nil {
		return m.OsmosisQueryContract
	}
	return ""
}

func (m *Params) GetOsmosisSwapContract() string {
	if m != nil {
		return m.OsmosisSwapContract
	}
	return ""
}

func (m *Params) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *Params) GetOsmosisExchangeRateUpdatePeriod() time.Duration {
	if m != nil {
		return m.OsmosisExchangeRateUpdatePeriod
	}
	return 0
}

func (m *Params) GetAccumulatedOsmosisFeeSwapPeriod() time.Duration {
	if m != nil {
		return m.AccumulatedOsmosisFeeSwapPeriod
	}
	return 0
}

func (m *Params) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "feeabstraction.absfee.v1beta1.Params")
}

func init() {
	proto.RegisterFile("feeabstraction/absfee/v1beta1/params.proto", fileDescriptor_64e66a0978c84086)
}

var fileDescriptor_64e66a0978c84086 = []byte{
	// 542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0xe3, 0xef, 0x6b, 0xd3, 0x74, 0x2a, 0xf1, 0xc7, 0x84, 0x60, 0x22, 0x70, 0xa2, 0xb0,
	0x89, 0x2a, 0xe1, 0x21, 0x85, 0x05, 0xb0, 0x0c, 0x01, 0xa9, 0x2b, 0x8a, 0x0b, 0x1b, 0x36, 0xd6,
	0xb5, 0x7d, 0xe3, 0x5a, 0xd8, 0x1e, 0xd7, 0x33, 0x4e, 0x9a, 0xb7, 0x60, 0xc9, 0x7b, 0xf0, 0x12,
	0x5d, 0x76, 0xc9, 0xaa, 0xa0, 0xe4, 0x0d, 0x78, 0x02, 0x34, 0xe3, 0x71, 0x94, 0x74, 0x83, 0x58,
	0x25, 0x93, 0x73, 0x7f, 0xe7, 0x9c, 0x1b, 0x8f, 0xc9, 0xe1, 0x14, 0x11, 0x7c, 0x2e, 0x0a, 0x08,
	0x44, 0xcc, 0x32, 0x0a, 0x3e, 0x9f, 0x22, 0xd2, 0xd9, 0xc8, 0x47, 0x01, 0x23, 0x9a, 0x43, 0x01,
	0x29, 0x77, 0xf2, 0x82, 0x09, 0x66, 0x3e, 0xde, 0x9e, 0x75, 0xaa, 0x59, 0x47, 0xcf, 0x76, 0xdb,
	0x11, 0x8b, 0x98, 0x9a, 0xa4, 0xf2, 0x5b, 0x05, 0x75, 0x1f, 0x45, 0x8c, 0x45, 0x09, 0x52, 0xc8,
	0x63, 0x0a, 0x59, 0xc6, 0x04, 0x48, 0x56, 0x5b, 0x76, 0x0f, 0x03, 0xc6, 0x53, 0xc6, 0xa9, 0x0f,
	0x1c, 0xe9, 0x79, 0x89, 0xc5, 0x62, 0x23, 0x3a, 0x8a, 0x33, 0x35, 0xac, 0x67, 0x6d, 0xed, 0xa4,
	0x4e, 0x7e, 0x39, 0xa5, 0x61, 0x59, 0x6c, 0xe8, 0x83, 0xef, 0xbb, 0xa4, 0x79, 0xa2, 0xfa, 0x9a,
	0x13, 0x72, 0x57, 0xf9, 0xc6, 0xdc, 0x8b, 0xfd, 0xc0, 0x0b, 0x31, 0x63, 0xa9, 0x65, 0xf4, 0x8d,
	0xe1, 0xfe, 0xd8, 0xfa, 0x7d, 0xdd, 0x6b, 0x2f, 0x20, 0x4d, 0x5e, 0x0f, 0x20, 0x49, 0xd8, 0x1c,
	0x43, 0x4f, 0xb0, 0x2f, 0x98, 0x0d, 0xdc, 0xdb, 0x1a, 0x39, 0xf6, 0x83, 0x89, 0x04, 0xcc, 0x31,
	0xb9, 0x23, 0x0b, 0xcc, 0x70, 0xc3, 0xe4, 0xbf, 0xbf, 0x98, 0xdc, 0xaa, 0x88, 0xb5, 0xc7, 0x11,
	0xb9, 0x5f, 0x37, 0x51, 0xeb, 0x79, 0xc1, 0x19, 0x64, 0x19, 0x26, 0xd6, 0xff, 0xd2, 0xc8, 0xbd,
	0xa7, 0xc5, 0x0f, 0x52, 0x7b, 0x53, 0x49, 0xe6, 0x4b, 0x62, 0xd5, 0x8c, 0x28, 0x20, 0xe3, 0x53,
	0x2c, 0xd6, 0xd8, 0x8e, 0xc2, 0x3a, 0x5a, 0xff, 0xa8, 0xe5, 0x9a, 0x7c, 0x46, 0xda, 0x35, 0xc9,
	0xe7, 0x90, 0xaf, 0xa9, 0x5d, 0x45, 0x99, 0x5a, 0x3b, 0x9d, 0x43, 0x5e, 0x13, 0x2f, 0x48, 0xe7,
	0x46, 0x3f, 0x96, 0xa9, 0x07, 0x6c, 0x35, 0x15, 0xd3, 0xde, 0x2a, 0xa8, 0xb5, 0xcd, 0xad, 0xaa,
	0x9c, 0x1a, 0xda, 0xdb, 0xda, 0x4a, 0x05, 0xd5, 0xcc, 0x03, 0xb2, 0x97, 0x33, 0x96, 0x78, 0x71,
	0x68, 0xb5, 0xfa, 0xc6, 0x70, 0xc7, 0x6d, 0xca, 0xe3, 0x71, 0x68, 0x9e, 0x93, 0x27, 0xb5, 0x19,
	0x5e, 0xc8, 0xc6, 0x11, 0x7a, 0x05, 0x08, 0xf4, 0xca, 0x3c, 0x94, 0x1f, 0x39, 0x16, 0x31, 0x0b,
	0xad, 0xfd, 0xbe, 0x31, 0x3c, 0x38, 0x7a, 0xe8, 0x54, 0xb7, 0xc0, 0xa9, 0x6f, 0x81, 0x33, 0xd1,
	0xb7, 0x60, 0xdc, 0xba, 0xbc, 0xee, 0x35, 0xbe, 0xfd, 0xec, 0x19, 0x6e, 0x4f, 0xfb, 0xbd, 0xd5,
	0x76, 0x2e, 0x08, 0xfc, 0xa4, 0xcc, 0x4e, 0x94, 0x97, 0x8c, 0x84, 0x20, 0x28, 0xd3, 0x32, 0x01,
	0x81, 0xa1, 0x57, 0xc7, 0x4f, 0x11, 0xab, 0x7d, 0x74, 0x24, 0xf9, 0x87, 0xc8, 0x0d, 0xbf, 0xf7,
	0x95, 0xdd, 0x3b, 0x44, 0xf9, 0x07, 0xe8, 0xc8, 0x0e, 0x69, 0xca, 0xd7, 0x66, 0x86, 0xd6, 0x41,
	0xdf, 0x18, 0xb6, 0x5c, 0x7d, 0x1a, 0x9f, 0x5e, 0x2e, 0x6d, 0xe3, 0x6a, 0x69, 0x1b, 0xbf, 0x96,
	0xb6, 0xf1, 0x75, 0x65, 0x37, 0xae, 0x56, 0x76, 0xe3, 0xc7, 0xca, 0x6e, 0x7c, 0x7e, 0x15, 0xc5,
	0xe2, 0xac, 0xf4, 0x9d, 0x80, 0xa5, 0x34, 0x63, 0x32, 0x0f, 0x92, 0xa7, 0x09, 0xf8, 0x9c, 0xde,
	0x78, 0x67, 0x67, 0x23, 0x7a, 0xa1, 0x7f, 0xa3, 0x62, 0x91, 0x23, 0xf7, 0x9b, 0xaa, 0xea, 0xf3,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x5e, 0xbc, 0x15, 0xde, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.AccumulatedOsmosisFeeSwapPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.AccumulatedOsmosisFeeSwapPeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x52
	n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.OsmosisExchangeRateUpdatePeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.OsmosisExchangeRateUpdatePeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x4a
	if m.PoolId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x40
	}
	if len(m.OsmosisSwapContract) > 0 {
		i -= len(m.OsmosisSwapContract)
		copy(dAtA[i:], m.OsmosisSwapContract)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OsmosisSwapContract)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.OsmosisQueryContract) > 0 {
		i -= len(m.OsmosisQueryContract)
		copy(dAtA[i:], m.OsmosisQueryContract)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OsmosisQueryContract)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.OsmosisSwapChannel) > 0 {
		i -= len(m.OsmosisSwapChannel)
		copy(dAtA[i:], m.OsmosisSwapChannel)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OsmosisSwapChannel)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OsmosisTransferChannel) > 0 {
		i -= len(m.OsmosisTransferChannel)
		copy(dAtA[i:], m.OsmosisTransferChannel)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OsmosisTransferChannel)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OsmosisQueryChannel) > 0 {
		i -= len(m.OsmosisQueryChannel)
		copy(dAtA[i:], m.OsmosisQueryChannel)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OsmosisQueryChannel)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NativeIbcDenom) > 0 {
		i -= len(m.NativeIbcDenom)
		copy(dAtA[i:], m.NativeIbcDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.NativeIbcDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OsmosisIbcDenom) > 0 {
		i -= len(m.OsmosisIbcDenom)
		copy(dAtA[i:], m.OsmosisIbcDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OsmosisIbcDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OsmosisIbcDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.NativeIbcDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OsmosisQueryChannel)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OsmosisTransferChannel)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OsmosisSwapChannel)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OsmosisQueryContract)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OsmosisSwapContract)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.PoolId != 0 {
		n += 1 + sovParams(uint64(m.PoolId))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.OsmosisExchangeRateUpdatePeriod)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.AccumulatedOsmosisFeeSwapPeriod)
	n += 1 + l + sovParams(uint64(l))
	if m.Active {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisIbcDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisIbcDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeIbcDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NativeIbcDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisQueryChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisQueryChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisTransferChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisTransferChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisSwapChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisSwapChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisQueryContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisQueryContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisSwapContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisSwapContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisExchangeRateUpdatePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.OsmosisExchangeRateUpdatePeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumulatedOsmosisFeeSwapPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.AccumulatedOsmosisFeeSwapPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
