// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feeabstraction/absfee/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the feeabs module.
type MsgSendQuerySpotPrice struct {
	FromAddress   string `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	PoolId        uint64 `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	SourcePort    string `protobuf:"bytes,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	SourceChannel string `protobuf:"bytes,4,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	BaseDenom     string `protobuf:"bytes,5,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty"`
	QuoteDenom    string `protobuf:"bytes,6,opt,name=quote_denom,json=quoteDenom,proto3" json:"quote_denom,omitempty"`
}

func (m *MsgSendQuerySpotPrice) Reset()         { *m = MsgSendQuerySpotPrice{} }
func (m *MsgSendQuerySpotPrice) String() string { return proto.CompactTextString(m) }
func (*MsgSendQuerySpotPrice) ProtoMessage()    {}
func (*MsgSendQuerySpotPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c172c34645b936, []int{0}
}
func (m *MsgSendQuerySpotPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendQuerySpotPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendQuerySpotPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendQuerySpotPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendQuerySpotPrice.Merge(m, src)
}
func (m *MsgSendQuerySpotPrice) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendQuerySpotPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendQuerySpotPrice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendQuerySpotPrice proto.InternalMessageInfo

func (m *MsgSendQuerySpotPrice) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgSendQuerySpotPrice) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *MsgSendQuerySpotPrice) GetSourcePort() string {
	if m != nil {
		return m.SourcePort
	}
	return ""
}

func (m *MsgSendQuerySpotPrice) GetSourceChannel() string {
	if m != nil {
		return m.SourceChannel
	}
	return ""
}

func (m *MsgSendQuerySpotPrice) GetBaseDenom() string {
	if m != nil {
		return m.BaseDenom
	}
	return ""
}

func (m *MsgSendQuerySpotPrice) GetQuoteDenom() string {
	if m != nil {
		return m.QuoteDenom
	}
	return ""
}

type MsgSendQuerySpotPriceResponse struct {
}

func (m *MsgSendQuerySpotPriceResponse) Reset()         { *m = MsgSendQuerySpotPriceResponse{} }
func (m *MsgSendQuerySpotPriceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendQuerySpotPriceResponse) ProtoMessage()    {}
func (*MsgSendQuerySpotPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c172c34645b936, []int{1}
}
func (m *MsgSendQuerySpotPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendQuerySpotPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendQuerySpotPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendQuerySpotPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendQuerySpotPriceResponse.Merge(m, src)
}
func (m *MsgSendQuerySpotPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendQuerySpotPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendQuerySpotPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendQuerySpotPriceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSendQuerySpotPrice)(nil), "feeabstraction.absfee.v1beta1.MsgSendQuerySpotPrice")
	proto.RegisterType((*MsgSendQuerySpotPriceResponse)(nil), "feeabstraction.absfee.v1beta1.MsgSendQuerySpotPriceResponse")
}

func init() {
	proto.RegisterFile("feeabstraction/absfee/v1beta1/tx.proto", fileDescriptor_84c172c34645b936)
}

var fileDescriptor_84c172c34645b936 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x6b, 0x36, 0x8a, 0xe6, 0x01, 0x07, 0x0b, 0x44, 0x54, 0xd1, 0x6c, 0x4c, 0x02, 0x0d,
	0x24, 0x62, 0x15, 0xb8, 0x20, 0x71, 0xe1, 0xc7, 0x85, 0xc3, 0xa4, 0xd1, 0xde, 0xb8, 0x54, 0x4e,
	0xf2, 0xea, 0x46, 0x4a, 0xfc, 0x3c, 0xdb, 0x99, 0xb6, 0xff, 0x80, 0xe3, 0xfe, 0x2c, 0x8e, 0x3d,
	0x22, 0x71, 0x41, 0xed, 0x3f, 0x82, 0x6c, 0x27, 0x48, 0xa0, 0xaa, 0x07, 0x6e, 0xc9, 0xc7, 0x9f,
	0xef, 0x7b, 0xcf, 0x7e, 0xf4, 0xd9, 0x02, 0x40, 0xe4, 0xd6, 0x19, 0x51, 0xb8, 0x0a, 0x15, 0x17,
	0xb9, 0x5d, 0x00, 0xf0, 0xcb, 0x49, 0x0e, 0x4e, 0x4c, 0xb8, 0xbb, 0xca, 0xb4, 0x41, 0x87, 0x6c,
	0xfc, 0xb7, 0x97, 0x45, 0x2f, 0xeb, 0xbc, 0xd1, 0x03, 0x89, 0x12, 0x83, 0xc9, 0xfd, 0x57, 0x0c,
	0x8d, 0x1e, 0x4b, 0x44, 0x59, 0x03, 0x17, 0xba, 0xe2, 0x42, 0x29, 0x74, 0xc2, 0x67, 0x6d, 0x77,
	0xfa, 0xa2, 0x40, 0xdb, 0xa0, 0xe5, 0xb9, 0xb0, 0xc0, 0x2f, 0x5a, 0x30, 0xd7, 0x7f, 0xda, 0x6a,
	0x21, 0x2b, 0x15, 0xe4, 0xde, 0xdd, 0x3d, 0xa6, 0x16, 0x46, 0x34, 0x7d, 0xdd, 0xe7, 0xbb, 0x5d,
	0xd0, 0x58, 0x2c, 0xa3, 0x7a, 0xf2, 0x93, 0xd0, 0x87, 0x67, 0x56, 0xce, 0x40, 0x95, 0x5f, 0xfc,
	0x00, 0x33, 0x8d, 0xee, 0xdc, 0x54, 0x05, 0xb0, 0x27, 0xf4, 0xee, 0xc2, 0x60, 0x33, 0x17, 0x65,
	0x69, 0xc0, 0xda, 0x84, 0x1c, 0x93, 0xd3, 0x83, 0xe9, 0xa1, 0x67, 0xef, 0x23, 0x62, 0x8f, 0xe8,
	0x1d, 0x8d, 0x58, 0xcf, 0xab, 0x32, 0xb9, 0x75, 0x4c, 0x4e, 0xf7, 0xa7, 0x43, 0xff, 0xfb, 0xb9,
	0x64, 0x47, 0xf4, 0xd0, 0x62, 0x6b, 0x0a, 0x98, 0x6b, 0x34, 0x2e, 0xd9, 0x0b, 0x51, 0x1a, 0xd1,
	0x39, 0x1a, 0xc7, 0x9e, 0xd2, 0xfb, 0x9d, 0x50, 0x2c, 0x85, 0x52, 0x50, 0x27, 0xfb, 0xc1, 0xb9,
	0x17, 0xe9, 0xc7, 0x08, 0xd9, 0x98, 0x52, 0xff, 0x36, 0xf3, 0x12, 0x14, 0x36, 0xc9, 0xed, 0xa0,
	0x1c, 0x78, 0xf2, 0xc9, 0x03, 0xdf, 0xe6, 0xa2, 0x45, 0xd7, 0x9f, 0x0f, 0x63, 0x9b, 0x80, 0x82,
	0x70, 0x72, 0x44, 0xc7, 0x5b, 0x2f, 0x37, 0x05, 0xab, 0x51, 0x59, 0x78, 0x75, 0x43, 0xe8, 0xde,
	0x99, 0x95, 0xec, 0x1b, 0xa1, 0x6c, 0xcb, 0x1b, 0xbc, 0xc9, 0x76, 0x2e, 0x3d, 0xdb, 0x5a, 0x7c,
	0xf4, 0xee, 0x7f, 0x52, 0xfd, 0x48, 0x1f, 0x66, 0xdf, 0xd7, 0x29, 0x59, 0xad, 0x53, 0xf2, 0x6b,
	0x9d, 0x92, 0x9b, 0x4d, 0x3a, 0x58, 0x6d, 0xd2, 0xc1, 0x8f, 0x4d, 0x3a, 0xf8, 0xfa, 0x56, 0x56,
	0x6e, 0xd9, 0xe6, 0x59, 0x81, 0x0d, 0x57, 0xe8, 0x2b, 0x8b, 0xfa, 0x65, 0x2d, 0x72, 0xcb, 0xff,
	0xd9, 0xf7, 0xe5, 0x84, 0x5f, 0x75, 0x8c, 0xbb, 0x6b, 0x0d, 0x36, 0x1f, 0x86, 0x6d, 0xbf, 0xfe,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x48, 0x8d, 0x43, 0x3d, 0xed, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SendQuerySpotPrice(ctx context.Context, in *MsgSendQuerySpotPrice, opts ...grpc.CallOption) (*MsgSendQuerySpotPriceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SendQuerySpotPrice(ctx context.Context, in *MsgSendQuerySpotPrice, opts ...grpc.CallOption) (*MsgSendQuerySpotPriceResponse, error) {
	out := new(MsgSendQuerySpotPriceResponse)
	err := c.cc.Invoke(ctx, "/feeabstraction.absfee.v1beta1.Msg/SendQuerySpotPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SendQuerySpotPrice(context.Context, *MsgSendQuerySpotPrice) (*MsgSendQuerySpotPriceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SendQuerySpotPrice(ctx context.Context, req *MsgSendQuerySpotPrice) (*MsgSendQuerySpotPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendQuerySpotPrice not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SendQuerySpotPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendQuerySpotPrice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendQuerySpotPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feeabstraction.absfee.v1beta1.Msg/SendQuerySpotPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendQuerySpotPrice(ctx, req.(*MsgSendQuerySpotPrice))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feeabstraction.absfee.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendQuerySpotPrice",
			Handler:    _Msg_SendQuerySpotPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feeabstraction/absfee/v1beta1/tx.proto",
}

func (m *MsgSendQuerySpotPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendQuerySpotPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendQuerySpotPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.QuoteDenom) > 0 {
		i -= len(m.QuoteDenom)
		copy(dAtA[i:], m.QuoteDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.QuoteDenom)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BaseDenom) > 0 {
		i -= len(m.BaseDenom)
		copy(dAtA[i:], m.BaseDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BaseDenom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SourcePort) > 0 {
		i -= len(m.SourcePort)
		copy(dAtA[i:], m.SourcePort)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourcePort)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PoolId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendQuerySpotPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendQuerySpotPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendQuerySpotPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSendQuerySpotPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PoolId != 0 {
		n += 1 + sovTx(uint64(m.PoolId))
	}
	l = len(m.SourcePort)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BaseDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.QuoteDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendQuerySpotPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSendQuerySpotPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendQuerySpotPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendQuerySpotPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourcePort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourcePort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuoteDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendQuerySpotPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendQuerySpotPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendQuerySpotPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
